blank_template = [
    {
        "badge_name": "cia",
        "code": "CIA",
        "file_name": "https://cdn.stux.media/badges/cia.png",
        "is_inverted": False,
    },
    {
        "badge_name": "discord",
        "code": "DISCORD",
        "file_name": "https://cdn.stux.media/badges/discord.png",
        "is_inverted": False,
    },
    {
        "badge_name": "cicada",
        "code": "CICADA",
        "file_name": "https://cdn.stux.media/badges/cicada.png",
        "is_inverted": False,
    },
    {
        "badge_name": "ioi",
        "code": "IOI",
        "file_name": "https://cdn.stux.media/badges/ioi.png",
        "is_inverted": False,
    },
    {
        "badge_name": "fbi",
        "code": "FBI",
        "file_name": "https://cdn.stux.media/badges/fbi.png",
        "is_inverted": False,
    },
    {
        "badge_name": "nsa",
        "code": "NSA",
        "file_name": "https://cdn.stux.media/badges/nsa.png",
        "is_inverted": False,
    },
    {
        "badge_name": "gab",
        "code": "GAB",
        "file_name": "https://cdn.stux.media/badges/gab.png",
        "is_inverted": False,
    },
    {
        "badge_name": "dop",
        "code": "DOP",
        "file_name": "https://cdn.stux.media/badges/dop.png",
        "is_inverted": False,
    },
    {
        "badge_name": "shit",
        "code": "SHIT",
        "file_name": "https://cdn.stux.media/badges/shit.png",
        "is_inverted": False,
    },
    {
        "badge_name": "bunker",
        "code": "BUNKER",
        "file_name": "https://cdn.stux.media/badges/bunker.png",
        "is_inverted": False,
    },
    {
        "badge_name": "dprk",
        "code": "DPRK",
        "file_name": "https://cdn.stux.media/badges/dprk.png",
        "is_inverted": False,
    },
    {
        "badge_name": "kek",
        "code": "KEK",
        "file_name": "https://cdn.stux.media/badges/kek.png",
        "is_inverted": False,
    },
    {
        "badge_name": "spacex",
        "code": "SpaceX",
        "file_name": "https://cdn.stux.media/badges/spacex.png",
        "is_inverted": False,
    },
    {
        "badge_name": "unsc",
        "code": "UNSC",
        "file_name": "https://cdn.stux.media/badges/unsc.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Anahein Ducks",
        "code": "ANA",
        "file_name": "https://cdn.stux.media/badges/ana.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Arizona Coyotes",
        "code": "ARI",
        "file_name": "https://cdn.stux.media/badges/ari.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Boston Bruins",
        "code": "BOS",
        "file_name": "https://cdn.stux.media/badges/bos.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Buffalo Sabres",
        "code": "BUF",
        "file_name": "https://cdn.stux.media/badges/buf.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Calgary Flames",
        "code": "CGY",
        "file_name": "https://cdn.stux.media/badges/cgy.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Carolina Hurricanes",
        "code": "CAR",
        "file_name": "https://cdn.stux.media/badges/car.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Chicago Blackhawks",
        "code": "CHI",
        "file_name": "https://cdn.stux.media/badges/chi.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Colorado Avalanche",
        "code": "COL",
        "file_name": "https://cdn.stux.media/badges/col.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Columbus Blue Jackets",
        "code": "CBJ",
        "file_name": "https://cdn.stux.media/badges/cbj.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Dallas Stars",
        "code": "DAL",
        "file_name": "https://cdn.stux.media/badges/dal.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Detroit Red Wings",
        "code": "DET",
        "file_name": "https://cdn.stux.media/badges/det.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Edmonton Oilers",
        "code": "EDM",
        "file_name": "https://cdn.stux.media/badges/edm.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Florida Panthers",
        "code": "FLA",
        "file_name": "https://cdn.stux.media/badges/fla.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Los Angeles Kings",
        "code": "LAK",
        "file_name": "https://cdn.stux.media/badges/lak.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Minnesota Wild",
        "code": "MIN",
        "file_name": "https://cdn.stux.media/badges/min.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Montréal Canadiens",
        "code": "MTL",
        "file_name": "https://cdn.stux.media/badges/mtl.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Nashville Predators",
        "code": "NSH",
        "file_name": "https://cdn.stux.media/badges/nsh.png",
        "is_inverted": False,
    },
    {
        "badge_name": "New Jersey Devils",
        "code": "NJD",
        "file_name": "https://cdn.stux.media/badges/njd.png",
        "is_inverted": False,
    },
    {
        "badge_name": "New York Islanders",
        "code": "NYI",
        "file_name": "https://cdn.stux.media/badges/nyi.png",
        "is_inverted": False,
    },
    {
        "badge_name": "New York Rangers",
        "code": "NYR",
        "file_name": "https://cdn.stux.media/badges/nyr.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Ottawa Senators",
        "code": "OTT",
        "file_name": "https://cdn.stux.media/badges/ott.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Philadelphia Flyers",
        "code": "PHI",
        "file_name": "https://cdn.stux.media/badges/phi.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Pittsburgh Penguins",
        "code": "PIT",
        "file_name": "https://cdn.stux.media/badges/pit.png",
        "is_inverted": False,
    },
    {
        "badge_name": "San Jose Sharks",
        "code": "SJS",
        "file_name": "https://cdn.stux.media/badges/sjs.png",
        "is_inverted": False,
    },
    {
        "badge_name": "St. Louis Blues",
        "code": "STL",
        "file_name": "https://cdn.stux.media/badges/stl.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Tampa Bay Lightning",
        "code": "TBL",
        "file_name": "https://cdn.stux.media/badges/tbl.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Toronto Maple Leafs",
        "code": "TOR",
        "file_name": "https://cdn.stux.media/badges/tor.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Vancouver Canucks",
        "code": "VAN",
        "file_name": "https://cdn.stux.media/badges/van.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Vegas Golden Knights",
        "code": "VGK",
        "file_name": "https://cdn.stux.media/badges/vgk.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Washington Capitals",
        "code": "WSH",
        "file_name": "https://cdn.stux.media/badges/wsh.png",
        "is_inverted": False,
    },
    {
        "badge_name": "Winnipeg Jets",
        "code": "WPG",
        "file_name": "https://cdn.stux.media/badges/wpg.png",
        "is_inverted": False,
    },
]
